# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\View\UI\TokenDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tokenDialog(object):
    def setupUi(self, tokenDialog):
        tokenDialog.setObjectName("tokenDialog")
        tokenDialog.resize(375, 168)
        self.gridLayout_2 = QtWidgets.QGridLayout(tokenDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tf_clientAppId = QtWidgets.QLineEdit(tokenDialog)
        self.tf_clientAppId.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tf_clientAppId.setObjectName("tf_clientAppId")
        self.gridLayout_2.addWidget(self.tf_clientAppId, 2, 2, 1, 1)
        self.lb_AccessToken = QtWidgets.QLabel(tokenDialog)
        self.lb_AccessToken.setObjectName("lb_AccessToken")
        self.gridLayout_2.addWidget(self.lb_AccessToken, 0, 0, 1, 1)
        self.ClientAppId = QtWidgets.QLabel(tokenDialog)
        self.ClientAppId.setObjectName("ClientAppId")
        self.gridLayout_2.addWidget(self.ClientAppId, 2, 0, 1, 1)
        self.lb_PlayerId = QtWidgets.QLabel(tokenDialog)
        self.lb_PlayerId.setObjectName("lb_PlayerId")
        self.gridLayout_2.addWidget(self.lb_PlayerId, 3, 0, 1, 1)
        self.tf_playerId = QtWidgets.QLineEdit(tokenDialog)
        self.tf_playerId.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tf_playerId.setObjectName("tf_playerId")
        self.gridLayout_2.addWidget(self.tf_playerId, 3, 2, 1, 1)
        self.tf_AssessToken = QtWidgets.QLineEdit(tokenDialog)
        self.tf_AssessToken.setText("")
        self.tf_AssessToken.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tf_AssessToken.setObjectName("tf_AssessToken")
        self.gridLayout_2.addWidget(self.tf_AssessToken, 0, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(tokenDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 4, 0, 1, 3)

        self.retranslateUi(tokenDialog)
        QtCore.QMetaObject.connectSlotsByName(tokenDialog)

    def retranslateUi(self, tokenDialog):
        _translate = QtCore.QCoreApplication.translate
        tokenDialog.setWindowTitle(_translate("tokenDialog", "Dialog"))
        self.lb_AccessToken.setText(_translate("tokenDialog", "assessToken"))
        self.ClientAppId.setText(_translate("tokenDialog", "clientAppId"))
        self.lb_PlayerId.setText(_translate("tokenDialog", "playerId"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tokenDialog = QtWidgets.QDialog()
    ui = Ui_tokenDialog()
    ui.setupUi(tokenDialog)
    tokenDialog.show()
    sys.exit(app.exec_())
